name: Build Arch Linux Installer for Radxa Rock 5

# Controls when the workflow will run
on:
  push:
    tags:
      - 'b*'
      - 'd*r5'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains two job
  build-rock-3588:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Extract U-Boot
        run: |
          curl -L https://github.com/radxa-repo/bullseye/raw/gh-pages/.pool/u-boot-rknext_2017.09-24-e919685_arm64.deb -o uboot.deb
          ar xv uboot.deb
          tar -xf data.tar.xz
          ls -l

      - name: Build Image for Rock 5B
        run: |
          bash <(curl -fsSL https://raw.githubusercontent.com/kwankiu/archlinux-installer-rock5/dev/create-installation-media) --kernel=linux-rockchip-joshua-git --model=rock5 --addpkg=linux-firmware-joshua-git -c --image=rock-5b-archlinux-installer.img --uboot=usr/lib/u-boot/rock-5b
          cp -r out/rock-5b-archlinux-installer.img.xz rock-5b-archlinux-installer.img.xz

#      - name: Build Image for Rock 5B Plus
#        run: |
#          bash <(curl -fsSL https://raw.githubusercontent.com/kwankiu/archlinux-installer-rock5/dev/create-installation-media) --kernel=linux-rockchip-joshua-git --model=rock5 --addpkg=linux-firmware-joshua-git -c --image=rock-5b-plus-archlinux-installer.img --uboot=usr/lib/u-boot/rock-5b-plus
#          cp -r out/rock-5b-plus-archlinux-installer.img.xz rock-5b-plus-archlinux-installer.img.xz

      - name: Build Image for Rock 5 ITX
        run: |
          bash <(curl -fsSL https://raw.githubusercontent.com/kwankiu/archlinux-installer-rock5/dev/create-installation-media) --kernel=linux-rockchip-joshua-git --model=rock5 --addpkg=linux-firmware-joshua-git -c --image=rock-5-itx-archlinux-installer.img --uboot=usr/lib/u-boot/rock-5-itx
          cp -r out/rock-5-itx-archlinux-installer.img.xz rock-5-itx-archlinux-installer.img.xz

      - uses: ncipollo/release-action@v1
        with:
            artifacts: "*-archlinux-installer.img.xz"
            makeLatest: false
            prerelease: true
            allowUpdates: true
            omitBody: true

  build-rock-3588s:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Extract U-Boot
        run: |
          curl -L https://github.com/radxa-repo/bullseye/raw/gh-pages/.pool/u-boot-rknext_2017.09-24-e919685_arm64.deb -o uboot.deb
          ar xv uboot.deb
          tar -xf data.tar.xz
          ls -l

      - name: Build Image for Rock 5A
        run: |
          bash <(curl -fsSL https://raw.githubusercontent.com/kwankiu/archlinux-installer-rock5/dev/create-installation-media) --kernel=linux-rockchip-joshua-git --model=rock5 --addpkg=linux-firmware-joshua-git -c --image=rock-5a-archlinux-installer.img --uboot=usr/lib/u-boot/rock-5a
          cp -r out/rock-5a-archlinux-installer.img.xz rock-5a-archlinux-installer.img.xz

#      - name: Build Image for Rock 5C
#        run: |
#          bash <(curl -fsSL https://raw.githubusercontent.com/kwankiu/archlinux-installer-rock5/dev/create-installation-media) --kernel=linux-rockchip-joshua-git --model=rock5 --addpkg=linux-firmware-joshua-git -c --image=rock-5c-archlinux-installer.img --uboot=usr/lib/u-boot/rock-5c
#          cp -r out/rock-5c-archlinux-installer.img.xz rock-5c-archlinux-installer.img.xz

      - name: Build Image for Radxa CM5
        run: |
          bash <(curl -fsSL https://raw.githubusercontent.com/kwankiu/archlinux-installer-rock5/dev/create-installation-media) --kernel=linux-rockchip-joshua-git --model=rock5 --addpkg=linux-firmware-joshua-git -c --image=radxa-cm5-archlinux-installer.img --uboot=usr/lib/u-boot/radxa-cm5-io
          cp -r out/radxa-cm5-archlinux-installer.img.xz radxa-cm5-archlinux-installer.img.xz

#      - name: Build Image for Radxa CM5 (RPI CM4 IO)
#        run: |
#          bash <(curl -fsSL https://raw.githubusercontent.com/kwankiu/archlinux-installer-rock5/dev/create-installation-media) --kernel=linux-rockchip-joshua-git --model=rock5 --addpkg=linux-firmware-joshua-git -c --image=radxa-cm5-rpi-cm4-io-archlinux-installer.img --uboot=usr/lib/u-boot/radxa-cm5-rpi-cm4-io
#          cp -r out/radxa-cm5-rpi-cm4-io-archlinux-installer.img.xz radxa-cm5-rpi-cm4-io-archlinux-installer.img.xz

      - name: Build Image for Radxa NX5
        run: |
          bash <(curl -fsSL https://raw.githubusercontent.com/kwankiu/archlinux-installer-rock5/dev/create-installation-media) --kernel=linux-rockchip-joshua-git --model=rock5 --addpkg=linux-firmware-joshua-git -c --image=radxa-nx5-archlinux-installer.img --uboot=usr/lib/u-boot/radxa-nx5-io
          cp -r out/radxa-nx5-archlinux-installer.img.xz radxa-nx5-archlinux-installer.img.xz

      - uses: ncipollo/release-action@v1
        with:
            artifacts: "*-archlinux-installer.img.xz"
            makeLatest: false
            prerelease: true
            allowUpdates: true
            omitBody: true