#  ____  ____  ____  __ _  ____  __  ____    ____  __ _  _  _  __  ____   __   __ _  _  _  ____  __ _  ____ 
# (    \(  __)/ ___)(  / )(_  _)/  \(  _ \  (  __)(  ( \/ )( \(  )(  _ \ /  \ (  ( \( \/ )(  __)(  ( \(_  _)
#  ) D ( ) _) \___ \ )  (   )( (  O )) __/   ) _) /    /\ \/ / )(  )   /(  O )/    // \/ \ ) _) /    /  )(  
# (____/(____)(____/(__\_) (__) \__/(__)    (____)\_)__) \__/ (__)(__\_) \__/ \_)__)\_)(_/(____)\_)__) (__) 
# List of Desktop Environment
desktop:
########################################################################
  # Minimum ACU Version
  - min_acu_verion: 0.0.7
########################################################################
  # Category List
  - categories:
      - category_name: Desktop
        category_description: Install a Desktop Environment
########################################################################
  # Desktop Environment List
  - items:
########################################################################
  # Items Usage / Examples
#      - package_name: Name to identify the package (small letter no space) (used for: acu install <package>)
#        pretty_name: Name to be shown on the app list (can contain capital letter and space) (used for: acu apps)
#        category: Specific a category that this package belongs to from the category_name of the list above
#        description: Description of the package 
#        compatible:
#          - Device tag list that this package is compatible with (this is optional when a package is suitable for any devices)
#        packages:
#          - Packages to be installed (this will be passed to acu install before running commands)
#        commands: |
#          # Commands to run when installing this packages
#          # This can be multiple lines
#          # This is mostly used for post install, which is optional

      # Gnome (Full)
      - package_name: gnome-full
        pretty_name: Gnome (Full)
        category: Desktop
        description: Comprehensive Gnome desktop with full suite
        compatible: null
        packages:
          - gnome
        commands: |
          sudo systemctl enable gdm

      # Gnome (Minimal)
      - package_name: gnome-minimal
        pretty_name: Gnome (Minimal)
        category: Desktop
        description: Comprehensive Gnome desktop with essentials only
        compatible: null
        packages:
          - gnome-shell
          - gnome-keyring
          - gnome-control-center
          - gnome-backgrounds
          - gnome-console
          - gnome-disk-utility
          - nautilus
          - xdg-user-dirs
          - gdm
          - librsvg
        commands: |
          sudo systemctl enable gdm

      # Phosh
      - package_name: phosh
        pretty_name: Phosh
        category: Desktop
        description: Experimental Phone shell based on the GNOME stack
        compatible: null
        packages:
          - phosh
          - gnome-keyring
          - gnome-control-center
          - gnome-backgrounds
          - gnome-console
          - gnome-disk-utility
          - nautilus
          - xdg-user-dirs
          - gdm
          - librsvg
        commands: |
          sudo systemctl enable gdm

      # KDE Plasma (Full)
      - package_name: plasma-full
        pretty_name: KDE Plasma (Full)
        category: Desktop
        description: KDE's comprehensive desktop with full suite
        compatible: null
        packages:
          - plasma-meta
          - sddm
          - kde-applications-meta
        commands: |
          sudo systemctl enable sddm

      # KDE Plasma (Minimal)
      - package_name: plasma-minimal
        pretty_name: KDE Plasma (Minimal)
        category: Desktop
        description: KDE's comprehensive desktop with essentials only
        compatible: null
        packages:
          - plasma-meta
          - sddm
          - konsole
          - dolphin
        commands: |
          sudo systemctl enable sddm

      # Budgie Desktop
      - package_name: budgie
        pretty_name: Budgie Desktop
        category: Desktop
        description: A lightweight Gnome-based desktop
        compatible: null
        packages:
          - budgie
          - arc-gtk-theme
          - papirus-icon-theme
          - gnome-keyring
          - gnome-console
          - gnome-disk-utility
          - nautilus
          - xdg-user-dirs
          - gdm
          - librsvg
        commands: |
          sudo systemctl enable gdm

      # Cutefish Desktop
      - package_name: cutefish
        pretty_name: Cutefish Desktop
        category: Desktop
        description: Elegant and uncluttered KDE-based desktop
        compatible: null
        packages:
          - plasma-desktop
          - sddm
          - cutefish
        commands: |
          sudo systemctl enable sddm

      # XFCE
      - package_name: xfce
        pretty_name: XFCE
        category: Desktop
        description: Lightweight GTK-based desktop
        compatible: null
        packages:
          - lightdm
          - lightdm-gtk-greeter
          - lightdm-gtk-greeter-settings
          - xorg-server
          - xfce4
          - xfce4-goodies
          - network-manager-applet
          - blueman
          - xdg-user-dirs
          - libmd
          - libbsd
          - librsvg
        commands: |
          sudo systemctl enable lightdm
          sudo systemctl enable accounts-daemon

      # LXQT
      - package_name: lxqt
        pretty_name: LXQT
        category: Desktop
        description: Lightweight Qt-based desktop
        compatible: null
        packages:
          - lxqt
          - breeze-icons
          - sddm
        commands: |
          sudo systemctl enable sddm

      # LXDE
      - package_name: lxde
        pretty_name: LXDE
        category: Desktop
        description: Lightweight X11 desktop
        compatible: null
        packages:
          - lxde
          - xscreensaver
        commands: |
          sudo systemctl enable lxdm

      # MATE
      - package_name: mate
        pretty_name: MATE
        category: Desktop
        description: Traditional Gnome 2-based desktop
        compatible: null
        packages:
          - mate
          - mate-extra
          - gdm
          - librsvg
        commands: |
          sudo systemctl enable gdm

      # Cinnamon
      - package_name: cinnamon
        pretty_name: Cinnamon
        category: Desktop
        description: Cinnamon Gnome-based desktop
        compatible: null
        packages:
          - cinnamon
          - cinnamon-translations
          - nemo-fileroller
          - nemo-image-converter
          - nemo-preview
          - xed
          - xreader
          - gnome-console
          - gdm
          - librsvg
        commands: |
          sudo systemctl enable gdm

      # Sway
      - package_name: sway
        pretty_name: Sway
        category: Desktop
        description: Tiling Wayland window manager
        compatible: null
        packages:
          - qt6-5compat
          - qt6-svg
          - sddm
          - sway
          - swayidle
          - swaylock
          - swaybg
          - swaync
          - waybar
          - rofi
          - xdg-desktop-portal-wlr
          - xdg-desktop-portal-gtk
          - xdg-user-dirs
          - polkit-gnome
          - foot
          - thunar
          - pass
        commands: |
          sudo systemctl enable sddm
          sudo mkdir -p /etc/sddm.conf.d
          sudo mkdir -p /usr/share/wayland-sessions
          #Sway Config
          sudo sed -i 's/set $menu /set $menu rofi -show drun #/g' /etc/sway/config
          sudo sed -i 's/bar {/exec waybar #/g' /etc/sway/config
          sudo sed -i 's/position top/#position top/g' /etc/sway/config
          mkdir -p /home/$(whoami)/.config/sway
          cp -r /etc/sway/config /home/$(whoami)/.config/sway/config

      # Hyprland
      - package_name: hyprland
        pretty_name: Hyprland
        category: Desktop
        description: Dynamic tiling Wayland window manager
        compatible: null
        packages:
          - qt6-5compat
          - qt6-svg
          - sddm
          - hyprland
          - hyprcursor
          - hyprpaper
          - hypridle
          - hyprlock
          - swaync
          - waybar
          - rofi
          - xdg-desktop-portal-hyprland
          - xdg-desktop-portal-gtk
          - xdg-user-dirs
          - polkit-gnome
          - alacritty
          - dolphin
          - pass
        commands: |
          sudo systemctl enable sddm
          sudo mkdir -p /etc/sddm.conf.d
          sudo mkdir -p /usr/share/wayland-sessions
          #Hyprland Config
          sudo sed -i 's/kitty/alacritty/g' /usr/share/hyprland/hyprland.conf
          sudo sed -i 's/wofi --show/rofi -show/g' /usr/share/hyprland/hyprland.conf
          sudo sed -i 's/# exec-once = waybar & hyprpaper & firefox/exec-once = waybar \& hyprpaper \& hypridle/g' /usr/share/hyprland/hyprland.conf
          mkdir -p /home/$(whoami)/.config/hypr
          cp -r /usr/share/hyprland/hyprland.conf /home/$(whoami)/.config/hypr/hyprland.conf
          #Hyprland Default Wallpaper
          echo -e "preload=/usr/share/hyprland/hyprland.png\nwallpaper=,contain:/usr/share/hyprland/hyprland.png" | sudo tee /home/$(whoami)/.config/hypr/hyprpaper.conf

      # Archcraft
      - package_name: archcraft
        pretty_name: Archcraft
        category: Desktop
        description: Archcraft DE with Openbox, Bspwm & i3wm
        compatible: null
        packages:
          - xorg-server
          - git
        commands: |
          echo "Installing Archcraft ARM ..."
          cd ~/.acu/cache
          sudo git clone --depth 1 https://github.com/archcraft-os/archcraft-arm
          cd archcraft-arm
          sudo curl -LO https://github.com/kwankiu/archlinux-installer/releases/download/kernel/0001-Config-for-installing-Archcraft-DE.patch
          sudo git apply 0001-Config-for-installing-Archcraft-DE.patch
          cd profile
          sudo ./install.sh
          # Fix permission issue
          sudo chown -R $(whoami) /home/$(whoami)

########################################################################