#  __ _  ____  ____  __ _  ____  __         
# (  / )(  __)(  _ \(  ( \(  __)(  )        
#  )  (  ) _)  )   //    / ) _) / (_/\      
# (__\_)(____)(__\_)\_)__)(____)\____/      
# List of available kernel and its drivers and packages
kernel:
  # Kernel List
  - items:
########################################################################
#      #Items Usage / Examples
#      - base: Kernel base package
#        description: Description of the kernel package
#        version: Linux kernel version
#        repo:
#          - Repositories to be added to pacman, supported formats are
#          - REPO_NAME
#          - REPO_NAME,REPO_URL (Coming Soon)
#          - REPO_NAME,REPO_URL,GPG_KEY (Coming Soon)
#        compatible:
#          - Device tags that this package is compatible with (or set to null if none)
#        recommended:
#          - Device tags that this package is the recommended option for that device (or set to null if none)
#        experimental:
#          - Device tags that this package is experimentally compatible with (or set to null if none)
#        firmware:
#          - linux firmware packages to install
#        graphics:
#          - graphics acceleration packages to install
#        video:
#          - video acceleration packages to install
#        additional:
#          - other packages to install

## Maintained by: ALARM ##
## Compatible with: Generic / All ##

      # Linux Mainline Kernel
      - base: linux-aarch64
        description: Linux Stable Kernel
        version: latest stable
        repo: null
        compatible:
          - generic
          - apple*
          - raspberrypi*
        recommended: null
        experimental:
          - radxa-zero*
          - radxa-rock-3*
          - radxa-rock-4*
          - radxa-rock-5*
          - khadas-vim*
          - khadas-edge*
          - xunlong-orangepi-5*
          - rockchip-rk3588-orangepi*
          - rockchip-rk3588s-orangepi*
        firmware: null
        graphics:
          - mesa
        video:
          - pipewire-jack
          - ffmpeg
        additional:
          - misc/grub

## Compatible with: Raspberry Pi ##

      # Linux Raspberry Pi Kernel
      - base: linux-rpi
        description: Linux Raspberry Pi BSP Kernel
        version: 6.12
        repo: null
        compatible:
          - raspberrypi*
        recommended:
          - raspberrypi*
        experimental: null
        firmware: null
        graphics:
          - mesa
        video:
          - pipewire-jack
          - ffmpeg-rpi
        additional: null

      # Linux Raspberry Pi 16K Kernel
      - base: linux-rpi-16k
        description: (For bcm2712/RPi5 ONLY) Linux Raspberry Pi BSP 16k pagesize Kernel
        version: 6.12
        repo: null
        compatible:
          - raspberrypi*
        recommended:
          - raspberrypi*
        experimental: null
        firmware: null
        graphics:
          - mesa
        video:
          - pipewire-jack
          - ffmpeg-rpi
        additional: null

## Maintained by: Samuel (kwankiu) / Joske / Asahi Linux ##
## Compatible with: Asahi Linux / Apple Silicon ##

      # Linux Asahi Kernel
      - base: linux-asahi
        description: Linux Asahi Kernel
        version: 6.11
        repo:
          - asahi
        compatible:
          - apple*
        recommended:
          - apple*
        experimental: null
        firmware:
          - asahi-fwextract
          - asahi-configs
        graphics:
          - mesa-asahi
        video:
          - pipewire-jack
          - ardour
          - asahi-audio
          - alsa-ucm-conf-asahi
          - ffmpeg
        additional: null

## Maintained by: 7Ji-PKGBUILDs / Joshua-Riek ##
## Compatible with: Rockchip ##

      # Joshua's Rockchip 6.1 Kernel
      - base: linux-aarch64-rockchip-bsp6.1-joshua-git
        description: Joshua Linux Rockchip BSP Kernel
        version: 6.1-rkr3
        repo:
          - 7Ji
        compatible:
          - radxa-rock-3*
          - radxa-rock-4*
          - radxa-rock-5*
          - radxa-cm5*
          - radxa-nx5*
          - radxa-zero3*
          - khadas-edge*
          - xunlong-orangepi-5*
          - rockchip-rk3588-orangepi*
          - rockchip-rk3588s-orangepi*
          - rockchip-rk3588-armsom*
          - friendlyelec-nanopi-r6*
          - friendlyelec-nanopc-*
          - friendlyelec-cm*
        recommended:
          - radxa-rock-5*
          - radxa-cm5*
          - radxa-nx5*
          - radxa-zero3*
          - khadas-edge*
          - xunlong-orangepi-5*
          - rockchip-rk3588-orangepi*
          - rockchip-rk3588s-orangepi*
          - rockchip-rk3588-armsom*
          - friendlyelec-nanopi-r6*
          - friendlyelec-nanopc-*
          - friendlyelec-cm*
        experimental: null
        firmware:
          - linux-firmware-joshua-git
        graphics:
          - mesa
        video:
          - pipewire-jack
          - ffmpeg-mpp-git
        additional: null

      # Joshua's Rockchip 5.10 Kernel
      - base: linux-aarch64-rockchip-bsp5.10-joshua-git
        description: Joshua Linux Rockchip BSP Kernel
        version: 5.10-rkr8
        repo:
          - 7Ji
        compatible:
          - radxa-rock-3*
          - radxa-rock-4*
          - radxa-rock-5*
          - radxa-cm5*
          - radxa-nx5*
          - radxa-zero3*
          - khadas-edge*
          - xunlong-orangepi-5*
          - rockchip-rk3588-orangepi*
          - rockchip-rk3588s-orangepi*
          - rockchip-rk3588-armsom*
          - friendlyelec-nanopi-r6*
          - friendlyelec-nanopc-*
          - friendlyelec-cm*
        recommended: null
        experimental: null
        firmware:
          - linux-firmware-joshua-git
        graphics:
          - mesa-panfork-git
          - mali-valhall-g610-firmware
          - libmali-valhall-g610-x11-wayland-gbm
        video:
          - pipewire-jack
          - ffmpeg-mpp-git
        additional: null

## Maintained by: 7Ji-PKGBUILDs / Radxa ##

      # Radxa Rockchip 5.10 Kernel
      - base: linux-aarch64-rockchip-bsp5.10-radxa-git
        description: Radxa Linux Rockchip BSP Kernel
        version: 5.10-rkr4.1
        repo:
          - 7Ji
        compatible:
          - radxa-rock-2*
          - radxa-rock-3*
          - radxa-rock-4*
          - radxa-rock-5*
          - radxa-cm3*
          - radxa-cm5*
          - radxa-nx5*
          - radxa-zero3*
        recommended: null
        experimental: null
        firmware:
          - 8852bu-dkms-git
          - 8852be-dkms-git
        graphics:
          - mesa-panfork-git
          - mali-valhall-g610-firmware
          - libmali-valhall-g610-x11-wayland-gbm
        video:
          - pipewire-jack
          - ffmpeg-mpp-git
        additional: null

      # Radxa Rockchip 6.1 Kernel
      - base: linux-aarch64-rockchip-bsp6.1-radxa
        description: Radxa Linux Rockchip BSP Kernel
        version: 6.1-rkr1
        repo:
          - rockchip
        compatible:
          - radxa-rock-2*
          - radxa-rock-3*
          - radxa-rock-4*
          - radxa-rock-5*
          - radxa-cm3*
          - radxa-cm5*
          - radxa-nx5*
          - radxa-zero3*
        recommended: null
        experimental: null
        firmware:
          - 8852bu-dkms-git
          - 8852be-dkms-git
        graphics:
          - mesa
        video:
          - pipewire-jack
          - ffmpeg-mpp-git
        additional: null

## Maintained by: 7Ji-PKGBUILDs / Orange Pi ##

      # Orange Pi Rockchip 5.10 Kernel
      - base: linux-aarch64-rockchip-rk3588-bsp5.10-orangepi-git
        description: OrangePi Linux Rockchip BSP Kernel
        version: 5.10.160
        repo:
          - 7Ji
        compatible:
          - xunlong-orangepi-5*
          - rockchip-rk3588s-orangepi*
          - rockchip-rk3588-orangepi*
        recommended:
          - xunlong-orangepi-5*
          - rockchip-rk3588s-orangepi*
          - rockchip-rk3588-orangepi*
        experimental: null
        firmware:
          - linux-firmware-orangepi-git
        graphics:
          - mesa-panfork-git
          - mali-valhall-g610-firmware
          - libmali-valhall-g610-x11-wayland-gbm
        video:
          - pipewire-jack
          - ffmpeg-mpp-git
        additional: null

## Maintained by: Samuel (kwankiu) / Fyde Innovations ##

      # FydeTab Rockchip BSP6.1 Kernel
      - base: linux-aarch64-rockchip-bsp6.1-fydetab-git
        description: FydeTab's fork of Joshua Linux Rockchip BSP Kernel
        version: 6.1-rkr3
        repo:
          - 7Ji
        compatible:
          - rockchip-rk3588s-tablet-12c-linux
          - rockchip-rk3588s-tablet-fydetab-linux
        recommended: null
        experimental: null
        firmware:
          - linux-firmware-joshua-git
        graphics:
          - mesa-panfork-git
          - mali-valhall-g610-firmware
          - libmali-valhall-g610-x11-wayland-gbm
        video:
          - pipewire-jack
          - ffmpeg-mpp-git
        additional: null

## Maintained by: Samuel (kwankiu) / Armbian ##

      # Armbian Rockchip BSP6.1 Kernel
      - base: linux-aarch64-rockchip-bsp6.1-armbian-git
        description: Armbian Linux Rockchip BSP Kernel
        version: 6.1-rkr5
        repo:
          - rockchip
        compatible:
          - radxa-rock-3*
          - radxa-rock-4*
          - radxa-rock-5*
          - radxa-cm5*
          - radxa-nx5*
          - radxa-zero3*
          - khadas-edge*
          - xunlong-orangepi-5*
          - rockchip-rk3588-orangepi*
          - rockchip-rk3588s-orangepi*
          - rockchip-rk3588-armsom*
          - friendlyelec-nanopi-r6*
          - friendlyelec-nanopc-*
          - friendlyelec-cm*
        recommended: null
        experimental: null
        firmware:
          - linux-firmware-armbian-git
        graphics:
          - mesa-panfork-git
        video:
          - pipewire-jack
          - ffmpeg-mpp-git
        additional: null

      # Armbian Rockchip Kernel
      - base: linux-aarch64-rockchip-armbian-git
        description: Armbian Linux Mainline Kernel with rockchip support
        version: 6.12.y
        repo:
          - rockchip
        compatible:
          - radxa-rock-3*
          - radxa-rock-4*
          - radxa-rock-5*
          - radxa-cm5*
          - radxa-nx5*
          - radxa-zero3*
          - khadas-edge*
          - xunlong-orangepi-5*
          - rockchip-rk3588-orangepi*
          - rockchip-rk3588s-orangepi*
          - rockchip-rk3588-armsom*
          - friendlyelec-nanopi-r6*
          - friendlyelec-nanopc-*
          - friendlyelec-cm*
        recommended: null
        experimental: null
        firmware:
          - linux-firmware-armbian-git
        graphics:
          - mesa
        video:
          - pipewire-jack
          - ffmpeg-mpp-git
        additional: null

## Maintained by: 7Ji-PKGBUILDs ##

      # Flippy's Kernel for Amlogic
      - base: linux-aarch64-flippy-git
        description: Flippy's Kernel aiming to increase usability for Amlogic
        version: 6.6
        repo:
          - 7Ji
        compatible:
          - khadas-vim*
          - radxa-zero
          - radxa-zero2
        recommended:
          - khadas-vim*
          - radxa-zero
          - radxa-zero2
        experimental: null
        firmware:
          - linux-aarch64-flippy-git-dtb-amlogic
          - linux-firmware-amlogic-ophub-git
        graphics:
          - mesa
        video:
          - pipewire-jack
          - ffmpeg
        additional:
          - ampart-git

      # Flippy's Kernel for Allwinner
      - base: linux-aarch64-flippy-git
        description: Flippy's Kernel aiming to increase usability for Allwinner
        version: 6.6
        repo:
          - 7Ji
        compatible:
          - friendlyarm-nanopi-neo*
          - xunlong-orangepi-zero*
        recommended:
          - friendlyarm-nanopi-neo*
          - xunlong-orangepi-zero*
        experimental: null
        firmware:
          - linux-aarch64-flippy-git-dtb-allwinner
        graphics:
          - mesa
        video:
          - pipewire-jack
          - ffmpeg
        additional: null

      # 7Ji's Mainline Kernel
      - base: linux-aarch64-7ji
        description: 7Ji Linux Mainline Kernel with patches for Amlogic & RK3588
        version: lastest stable
        repo:
          - 7Ji
        compatible:
          - khadas-vim*
          - khadas-edge
          - radxa-zero*
          - radxa-rock-3*
          - radxa-rock-4*
        recommended: null
        experimental:
          - radxa-rock-5*
          - khadas-edge2
          - xunlong-orangepi-5*
          - rockchip-rk3588-orangepi*
          - rockchip-rk3588s-orangepi*
          - rockchip-rk3588-armsom*
        firmware: null
        graphics:
          - mesa
        video:
          - pipewire-jack
          - ffmpeg-mpp-git
        additional: null

########################################################################
