#  __ _  ____  ____  __ _  ____  __         
# (  / )(  __)(  _ \(  ( \(  __)(  )        
#  )  (  ) _)  )   //    / ) _) / (_/\      
# (__\_)(____)(__\_)\_)__)(____)\____/      
# List of available kernel and its drivers and packages
kernel:
  # Kernel List
  - items:
########################################################################
  # Items Usage / Examples
#      - base: Kernel base package
#        description: Description of the kernel package 
#        compatible:
#          - Device tag list that this package is compatible with (this is optional when a package is suitable for any devices)
#        packages:
#          - Packages to be installed (this will be passed to acu install before running commands)
#        commands: |
#          # Commands to run when installing this packages
#          # This can be multiple lines
#          # This is mostly used for post install, which is optional

      # Linux Mainline Kernel
      - base: linux-aarch64
        description: Linux Mainline Kernel
        version: 6.x
        repo: null
        compatible: null
        firmware:
          - linux-firmware
        graphics:
          - mesa
        video:
          - ffmpeg
        others: null
        commands: null


########################################################################