#  ____   __   ____  ____    __  __ _  ____  ____  __   __    __   
# (  _ \ /  \ / ___)(_  _)  (  )(  ( \/ ___)(_  _)/ _\ (  )  (  )  
#  ) __/(  O )\___ \  )(     )( /    /\___ \  )( /    \/ (_/\/ (_/\
# (__)   \__/ (____/ (__)   (__)\_)__)(____/ (__)\_/\_/\____/\____/
# Post Installation for SBCs
postinstall:
########################################################################
  # Minimum ACU Version
  - min_acu_verion: 0.0.7
########################################################################
  # Category List
  - categories:
      - category_name: Post-Install
        category_description: Post Installation for SBCs
########################################################################
  # Post Install List
  - items:
########################################################################
  # Items Usage / Examples
#      - package_name: Name to identify the package (small letter no space) (used for: acu install <package>)
#        pretty_name: Name to be shown on the app list (can contain capital letter and space) (used for: acu apps)
#        category: Specific a category that this package belongs to from the category_name of the list above
#        description: Description of the package 
#        compatible:
#          - Device tag list that this package is compatible with (this is optional when a package is suitable for any devices)
#        packages:
#          - Packages to be installed (this will be passed to acu install before running commands)
#        commands: |
#          # Commands to run when installing this packages
#          # This can be multiple lines
#          # This is mostly used for post install, which is optional

      # Disable Suspend
      - package_name: disable-suspend
        pretty_name: Disable Suspend
        category: Post-Install
        description: Disable System Suspend
        compatible:
          - radxa-rock-5*
          - radxa-cm5*
          - radxa-nx5*
          - xunlong-orangepi-5*
          - rockchip-rk3588s-orangepi*
          - rockchip-rk3588-orangepi*
        commands: |
          echo "Disable suspend ..."
          sudo mkdir -p /usr/lib/systemd/system/sleep.conf.d
          echo -e "[Sleep]\nAllowSuspend=no\nAllowHibernation=no\nAllowSuspendThenHibernate=no\nAllowHybridSleep=no" | sudo tee /usr/lib/systemd/system/sleep.conf.d/nosuspend.conf

      # FAN control for Khadas Edge 2
      - package_name: khadas-edges-fan-control
        pretty_name: Khadas Fan Control
        category: Post-Install
        description: FAN control for Khadas Edge 2
        compatible:
          - khadas-edge*
        commands: |
          echo "Installing FAN control for Edge 2 ..."
          curl -LJO https://raw.githubusercontent.com/khadas/fenix/master/archives/filesystem/special/Edge2/usr/local/bin/fan.sh
          sudo chmod +x fan.sh
          sudo mv fan.sh /usr/local/bin/fan.sh
          echo "Creating FAN control service ..."
          echo -e "[Unit]\nDescription=FAN control\nDefaultDependencies=no\nAfter=local-fs.target\n\n[Service]\nExecStart=/usr/bin/sudo /usr/local/bin/fan.sh\nRemainAfterExit=no\n\n[Install]\nWantedBy=sysinit.target" | sudo tee /usr/lib/systemd/system/fan.service
          sudo systemctl enable fan.service

      # AP6275P Fixup
      - package_name: ap6275p-fixup
        pretty_name: AP6275P Fixup
        category: Post-Install
        description: Fix networkmanager & enable bluetooth for AP6275P
        compatible:
          - khadas-edge*
          - xunlong-orangepi-5*
          - rockchip-rk3588s-orangepi*
          - rockchip-rk3588-orangepi*
          - rockchip-rk3588-armsom*
          - fydeos-fydetab*
          - rockchip-rk3588s-tablet-12c-linux
        commands: |
          #1 Switch Network Manager to iwd
          echo "Switch WiFi backend to iwd ..."
          sudo mkdir -p /etc/NetworkManager/conf.d
          echo -e "[device]\nwifi.backend=iwd" | sudo tee /etc/NetworkManager/conf.d/wifi_backend.conf
          sudo rm -rf /etc/netctl/*
          #2 Enable AP6275P bluetooth
          echo "Enable AP6275P Bluetooth ..."
          curl -LJO https://github.com/kwankiu/archlinux-installer/releases/download/kernel/brcm_patchram_plus
          sudo chmod +x brcm_patchram_plus
          sudo mv brcm_patchram_plus /usr/bin/brcm_patchram_plus
          echo -e '[Unit]\nDescription=AP6275P Bluetooth service\nAfter=bluetooth.target\n\n[Service]\nType=forking\nExecStartPre=/usr/sbin/rfkill unblock all\nExecStart=/usr/bin/brcm_patchram_plus --enable_hci --no2bytes --use_baudrate_for_download --tosleep 200000 --baudrate 1500000 --patchram /lib/firmware/ap6275p/BCM4362A2.hcd /dev/ttyS9\nTimeoutSec=0\nRemainAfterExit=yes\n[Install]\nWantedBy=multi-user.target' | sudo tee /usr/lib/systemd/system/bt_ap6275p.service
          sudo systemctl enable bt_ap6275p.service

      # Asahi mkinitpcio conf
      - package_name: asahi-mkinitcpio-conf
        pretty_name: Asahi mkinitpcio conf
        category: Post-Install
        description: Add asahi hook and modules to mkinitcpio conf
        compatible:
          - apple*
        commands: |
          echo "Add asahi hook and modules to mkinitcpio conf ..."
          sudo sed -i 's/MODULES=()/MODULES=(ext4 btrfs usbhid xhci_hcd)/g' /etc/mkinitcpio.conf
          sudo sed -i 's/HOOKS=(base /HOOKS=(base asahi /g' /etc/mkinitcpio.conf

      # RK3588 USB2 HOST
      - package_name: rk3588-usb2-host
        pretty_name: RK3588 USB2 Host
        category: Post-Install
        description: Set RK3588 USB2.0 OTG mode to host
        compatible:
          - xunlong-orangepi-5*
          - rockchip-rk3588s-orangepi*
          - rockchip-rk3588-orangepi*
        commands: |
          echo "Enable the USB 2.0 port ..."
          echo -e "[Unit]\nDescription=Enable the USB 2.0 port\n\n[Service]\nExecStart=/usr/bin/sh -c \\"echo host > /sys/kernel/debug/usb/fc000000.usb/mode\\"\nType=oneshot\n\n[Install]\nWantedBy=default.target" | sudo tee /usr/lib/systemd/system/enable-usb2.service
          sudo systemctl enable enable-usb2

########################################################################
