name: Build Arch Linux Installer (U-Boot + Extlinux)

# Controls when the workflow will run
on:
  push:
    tags:
      - 'b*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Build Images
    permissions:
      contents: write

    strategy:
      matrix:
        model_name:
          # Generic
          #- generic
          # Raspberry Pi
          - raspberrypi
          # Radxa
          #- radxa-rock-2a
          #- radxa-rock-2f
          #- radxa-rock-3a
          #- radxa-rock-3b
          #- radxa-rock-3c
          - radxa-rock-5a
          - radxa-rock-5b
          - radxa-rock-5b-plus
          - radxa-rock-5c
          - radxa-rock-5d
          - radxa-rock-5-itx
          #- radxa-cm3-io
          #- radxa-cm3-rpi-cm4-io
          #- radxa-cm3-sodimm-io
          #- radxa-cm3i-io
          #- radxa-e23
          #- radxa-e25
          - radxa-cm5-io
          - radxa-cm5-rpi-cm4-io
          - radxa-nx5-io
          - radxa-zero3
          # Khadas
          - khadas-edge
          - khadas-edge2
          # Orange Pi
          - orangepi-5 #rockchip-rk3588s-orangepi-5
          - orangepi-5b
          - orangepi-5-plus
          - orangepi-5-pro
          - orangepi-5-max
          - orangepi-cm5
          #- orangepi-3b
          # Nano Pi
          - nanopc-t6
          - nanopi-r6c
          - nanopi-r6s
          #- nanopi-cm3588
          # Other Rockchip RK35XX
          #- indiedroid-nova #9tripod-rk3588s
          #- mixtile-blade3 #rockchip-rk3588-blade3-v101-linux
          #- mixtile-core3588e
          #- embedfire-lubancat-4 #rockchip-rk3588s-lubancat-4
          #- turing-rk1
          - armsom-sige7 #rockchip-rk3588-armsom-sige7
          - armsom-aim7 #rockchip-rk3588-armsom-aim7
          - armsom-w3 #rockchip-rk3588-armsom-w3
          # Others
          # Add more models as needed

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Preparing
        run: |
          for model in ${{ matrix.model_name }}; do
            echo "Building image for $model"
            case $model in
              raspberrypi)
                # Notes: Raspberry Pi does not use extlinux and does not need to pack u-boot
                args="--kernel=linux-rpi --addpkg=firmware-raspberrypi -b --bootpartstart=4MiB --bootloader=skip"
                ;;
              radxa-*)
                # Use different kernel and u-boot path for different boards
                if [[ "$model" == "radxa-rock"* ]]; then
                  args="--kernel=linux-aarch64-rockchip-bsp6.1-joshua-git --addpkg=linux-firmware-joshua-git --bootfirmware=usr/lib/u-boot/${model#*-}"
                else
                  args="--kernel=linux-aarch64-rockchip-bsp6.1-joshua-git --addpkg=linux-firmware-joshua-git --bootfirmware=usr/lib/u-boot/${model}"
                fi
                # URL to download u-boot for the board
                if [[ "$model" == "radxa-zero"* ]]; then
                  uboot_url="https://github.com/radxa-repo/bullseye/raw/gh-pages/.pool/u-boot-latest_2023.10-9-eed05a18_arm64.deb"
                else
                  uboot_url="https://github.com/kwankiu/archlinux-installer/releases/download/kernel/uboot-radxa-rknext_2017.09-1_arm64.deb"
                  # uboot_url="https://github.com/radxa-repo/bullseye/raw/gh-pages/.pool/u-boot-rknext_2017.09-25-f348cc9_arm64.deb"
                fi
                ;;
              khadas-*)
                args="--kernel=linux-aarch64-rockchip-bsp6.1-joshua-git --addpkg=linux-firmware-joshua-git --bootfirmware=usr/lib/u-boot"
                # URL to download u-boot for the board
                if [ "$model" == "khadas-edge2" ]; then
                    uboot_url="https://dl.khadas.com/repos/edge2/pool/main/l/linux-u-boot-edge2-vendor/linux-u-boot-edge2-vendor_1.6.8-2017.09_arm64.deb"
                elif [ "$model" == "khadas-edge" ]; then
                    uboot_url="https://dl.khadas.com/repos/edge/pool/main/l/linux-u-boot-edge-vendor/linux-u-boot-edge-vendor_0.8.3-2017.09_arm64.deb"
                fi
                ;;
              orangepi-* | nanopi-* | nanopc-* | armsom-*)
                args="--kernel=linux-aarch64-rockchip-bsp6.1-joshua-git --addpkg=linux-firmware-joshua-git --bootfirmware=usr/lib/u-boot -b"
                # URL to download u-boot for the board
                uboot_url="https://launchpad.net/~jjriek/+archive/ubuntu/rockchip/+files/u-boot-${model}_2017.09+20240626.git5202c429-4_arm64.deb"
                ;;
              *)
                # Generic
                args="--kernel=linux -b"
                ;;
            esac
          done
          echo "ARGS=$args" >> $GITHUB_ENV
          echo "UBOOT_URL=$uboot_url" >> $GITHUB_ENV
  
      - name: Extract U-Boot
        if: ${{ env.UBOOT_URL }}
        env:
          uboot_url: ${{ env.UBOOT_URL }}
        run: |
          curl -L ${uboot_url} -o uboot.deb
          ar xv uboot.deb
          if [ -f "data.tar.xz" ]; then
            tar -xf data.tar.xz
          elif [ -f "data.tar.zst" ]; then
            tar -xI unzstd -f data.tar.zst
          fi
          ls -l

      - name: Build Image
        env:
          args: ${{ env.ARGS }}
        run: |
          bash <(curl -fsSL https://raw.githubusercontent.com/kwankiu/archlinux-installer/main/create-installation-media) --model=${{ matrix.model_name }} --image=${{ matrix.model_name }}-archlinux-installer.img -c $args
          cp -r out/*-archlinux-*.img.xz .

      - name: Add meta data to Image (OOWOW)
        if: startsWith(matrix.model_name, 'khadas')
        run: |
          bash <(curl -fsSL https://raw.githubusercontent.com/khadas/krescue/master/tools/xze) "${{ matrix.model_name }}-archlinux-installer.img.xz" \
             --meta \
             label="Arch Linux Installer" \
             builder="Arch Linux Installer" \
             date="$(LANG=C TZ= date)" \
             match=BOARD=$(echo "${{ matrix.model_name }}" | awk -F'-' '{print toupper(substr($2,1,1)) substr($2,2)}') \
             link=https://github.com/kwankiu/archlinux-installer/wiki \
             duration=250 \
             desc="Community-built Arch Linux Installer for ARM (Aarch64), Image built for $(echo "${{ matrix.model_name }}" | sed 's/-/ /g; s/\b\(.\)/\u\1/g')"
          # Rename image name to begin with the board model (required to prevent OOWOW hiding the image)
          mv ${{ matrix.model_name }}-archlinux-installer.img.xz $(echo "${{ matrix.model_name }}" | awk -F'-' '{print substr($2,1)}')-khadas-archlinux-installer.img.xz
        continue-on-error: true

      - name: Upload to GitHub Release
        uses: ncipollo/release-action@v1
        with:
            artifacts: "*-archlinux-*.img.xz"
            makeLatest: false
            allowUpdates: true
            omitBody: true